# If you add a page, you must add it to the index here
nav:
  - Home:
      - Home: 'index.md'
  - 3.0.0 Documentation:
      - Installation: '3.0.0/index.md'
      - Getting Started: '3.0.0/getting_started.md'
      - Model Classes: '3.0.0/models.md'
      - Animation Types:
          - Entity Animations: '3.0.0/entity_animations.md'
          - Block Animations: '3.0.0/block_animations.md'
          - Item Animations: '3.0.0/item_animations.md'
          - Armor Animations: '3.0.0/armor_animations.md'
      - Animation Basics: '3.0.0/the_basics.md'
      - Sounds, Particles, and Events: '3.0.0/effect_keyframes.md'
      - Molang: '3.0.0/molang.md'
      - The Bedrock Renderer: '3.0.0/bedrock_renderer.md'
      - Custom Model Providers: '3.0.0/custom_model_providers.md'
      - Miscellaneous Topics: '3.0.0/misc.md'
      - Upgrading from GeckoLib 2.0.0: '3.0.0/upgrading.md'
      - Examples: '3.0.0/examples.md'
      - Shadowing: '3.0.0/shadowing.md'
      - FAQs: '3.0.0/faqs.md'
      - Contributing: '3.0.0/contributing.md'
      - Roadmap: '3.0.0/todo.md'



repo_name: GeckoLib
repo_url: https://github.com/bernie-g/geckolib
# Do not edit in PRs below here
site_name: ' '
edit_uri: ""
theme:
  name: material
  custom_dir: theme/material/overrides
  font:
    code: GravityBold
  favicon: 'images/favicon.png'
  logo: 'images/geckolib_webtitle.png'
  features:
    - navigation.tabs
    - navigation.expand

extra_css:
  - 'stylesheet/extra_stylesheet.css'

markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - pymdownx.keys
  - lightgallery
  - codehilite:
      guess_lang: false
      use_pygments: true
      linenums: true
  - attr_list
plugins:
  - macros
  - search


# Variables used to determine the most updated gradle snippet for each geckolib version. These update in the docs automatically
extra:
  version_info_2:
      forge_1_12: 'software.bernie.geckolib:forge-1.12.2-geckolib:2.0.2'
      forge_1_15: 'software.bernie.geckolib:forge-1.15.2-geckolib:2.0.0'
      forge_1_16: 'software.bernie.geckolib:forge-1.16.3-geckolib:2.1.1'
      fabric_1_15: 'software.bernie.geckolib:fabric-1.15.2-geckolib:2.0.0:dev'
      fabric_1_16: 'software.bernie.geckolib:fabric-1.16.2-geckolib:2.0.0:dev'
  version_info_3:
      forge_1_12: 'software.bernie.geckolib:forge-1.12.2-geckolib:3.0.0-beta.5'
      forge_1_15: 'software.bernie.geckolib:geckolib-forge-1.15.2:3.0.13'
      forge_1_16: 'software.bernie.geckolib:geckolib-forge-1.16.5:3.0.13'
      fabric_1_16: 'software.bernie.geckolib:geckolib-fabric-1.16.5:3.0.20:dev'

